name: BuildAssets

on:
  push:
    branches: 
      - master
  workflow_dispatch:


jobs:
  deploy_to_wpengine:
    name: Build Assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Build static assets
        run: |
          npm install
          npm run build
          git add .
          git commit -m "build assets"

