name: BuildAssets

on:
  push:
    branches: 
      - master
  workflow_dispatch:


jobs:
  build_assets:
    name: Build Assets
    runs-on: ubuntu-latest
    steps:

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build static assets
        run: |
          ls -la

